# Generated by Django 5.2.8 on 2025-11-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
